version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached
      - /app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: yarn dev
