version: '3.9'
services:
  popu-checker:
    container_name: popu-checker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:cached
      - /app/node_modules
    tty: true
    ports:
      - '3000:3000'
    # command: npm run dev
